apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 212437578314.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 212437578314.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 7ffa09c1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
